// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAPIG0qZkfuRnqIRHZWhtdEDaJIbDzW7ys',
    appId: '1:423345341751:web:572e0f78afb133c2f886b2',
    messagingSenderId: '423345341751',
    projectId: 'tutorgenie-56480',
    authDomain: 'tutorgenie-56480.firebaseapp.com',
    storageBucket: 'tutorgenie-56480.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBY5g7Ikni5Xf41TUyXkGDzuSa7vXaSamY',
    appId: '1:423345341751:android:e22664c5e68d8010f886b2',
    messagingSenderId: '423345341751',
    projectId: 'tutorgenie-56480',
    storageBucket: 'tutorgenie-56480.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDL3-cwTzpsG6YcdW2atYl1Rv1aD2nYZeI',
    appId: '1:423345341751:ios:d7aba512a0a9d5f8f886b2',
    messagingSenderId: '423345341751',
    projectId: 'tutorgenie-56480',
    storageBucket: 'tutorgenie-56480.appspot.com',
    iosClientId: '423345341751-9bf8dric2623obapk396gv3ghfbm3m3t.apps.googleusercontent.com',
    iosBundleId: 'com.example.tutorgenie',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDL3-cwTzpsG6YcdW2atYl1Rv1aD2nYZeI',
    appId: '1:423345341751:ios:d7aba512a0a9d5f8f886b2',
    messagingSenderId: '423345341751',
    projectId: 'tutorgenie-56480',
    storageBucket: 'tutorgenie-56480.appspot.com',
    iosBundleId: 'com.example.tutorgenie',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAPIG0qZkfuRnqIRHZWhtdEDaJIbDzW7ys',
    appId: '1:423345341751:web:8c587f932c42ade3f886b2',
    messagingSenderId: '423345341751',
    projectId: 'tutorgenie-56480',
    authDomain: 'tutorgenie-56480.firebaseapp.com',
    storageBucket: 'tutorgenie-56480.appspot.com',
  );
}